events {
}

http {

    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name faqchuvsu;
        ssl_certificate "/etc/ssl/faqchuvsu+2.pem";
        ssl_certificate_key "/etc/ssl/faqchuvsu+2-key.pem";

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Ssl on;
            proxy_set_header Host $host;
            proxy_pass http://faq:3000;
        }
    }
}